// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQRUnIkhQ8AbowQljamy3VYXtofpwaWqk',
    appId: '1:983758616880:web:4b14a8b35c5a68296eb0f5',
    messagingSenderId: '983758616880',
    projectId: 'pathlly',
    authDomain: 'pathlly.firebaseapp.com',
    storageBucket: 'pathlly.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASMWGFsmUAmVzB4Yx76zY84Sbkiq3AZuA',
    appId: '1:983758616880:android:f5e6713a1c8fcc1d6eb0f5',
    messagingSenderId: '983758616880',
    projectId: 'pathlly',
    storageBucket: 'pathlly.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQRUnIkhQ8AbowQljamy3VYXtofpwaWqk',
    appId: '1:983758616880:web:a8b98f612d52f7b76eb0f5',
    messagingSenderId: '983758616880',
    projectId: 'pathlly',
    authDomain: 'pathlly.firebaseapp.com',
    storageBucket: 'pathlly.firebasestorage.app',
  );
}
